spring:
  application:
    name: sequence-words-api
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migrations

springdoc:
  swagger-ui:
    enabled: false
    default-models-expand-depth: -1
  packages-to-scan: com.well.sequencewordsapi

scalar:
  enabled: true
  path: /docs
  url: /v3/api-docs

security:
  cors:
    allowed-origin: ${CORS_ALLOWED_ORIGIN}

auth:
  jwt:
    issuer: sequence-words-api
    secret: ${JWT_SECRET}
    ttlSeconds: ${JWT_TTL_SECONDS:-86400}